# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 16:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proj',
            fields=[
                ('project', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proj',
            },
        ),
        migrations.CreateModel(
            name='req',
            fields=[
                ('url', models.URLField()),
                ('method', models.CharField(max_length=10)),
                ('data_form', models.CharField(max_length=10)),
                ('header', django.contrib.postgres.fields.jsonb.JSONField()),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tag', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_proj', to='formsapp.proj')),
            ],
            options={
                'db_table': 'req',
            },
        ),
        migrations.CreateModel(
            name='res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_proj', to='formsapp.proj')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restag', to='formsapp.req')),
            ],
            options={
                'db_table': 'res',
            },
        ),
    ]
